# Generated by Django 5.2.1 on 2025-06-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_email_remove_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Nom d'utilisateur"),
        ),
    ]
