# Generated by Django 5.2.1 on 2025-06-05 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='classe',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='classe'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
    ]
