# Generated by Django 5.2.1 on 2025-06-04 10:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('processed_text', models.TextField(blank=True, null=True)),
                ('detected_type', models.CharField(choices=[('exercice', 'Exercice'), ('resume', 'Résumé'), ('cours', 'Cours'), ('inconnu', 'Inconnu')], default='inconnu', max_length=20)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scanned_texts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
